#!/usr/bin/env python3
"""Compile config and ordered Plymouth modules into the distributable theme.

The generated theme/curruption.script is committed so the theme can be
installed without a Python toolchain. Regenerate it with ./scripts/build.sh
after editing config/theme.conf or anything under theme/modules/.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config/theme.conf"
MODULES = ROOT / "theme/modules"
GENERATED = MODULES / "00-config.script"
OUTPUT = ROOT / "theme/curruption.script"

# Every key the runtime reads. A missing key is a build failure rather than a
# NULL dereference on somebody's boot screen.
REQUIRED = (
    "animation_duration",
    "animation_speed",
    "refresh_rate",
    "compat_profile",
    "gore_enabled",
    "jaw_open_distance",
    "blood_overlay_opacity",
    "dangling_eye_enabled",
    "dangling_eye_sway",
    "dangling_eye_speed",
    "big_brother_eye_enabled",
    "eye_duration",
    "smoke_density",
    "glitch_intensity",
    "film_grain",
    "vignette_opacity",
    "hud_enabled",
    "random_seed",
)


def read_config() -> dict[str, str]:
    values: dict[str, str] = {}
    for number, raw in enumerate(CONFIG.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise SystemExit(f"{CONFIG.name}:{number}: expected key=value, got {line!r}")
        key, value = line.split("=", 1)
        key, value = key.strip(), value.strip()
        try:
            float(value)
        except ValueError:
            raise SystemExit(
                f"{CONFIG.name}:{number}: {key} must be numeric, got {value!r}"
            ) from None
        values[key] = value
    return values


def main() -> None:
    values = read_config()
    missing = [key for key in REQUIRED if key not in values]
    if missing:
        raise SystemExit(f"Missing configuration: {', '.join(missing)}")

    lines = [
        "# Generated by scripts/build.py from config/theme.conf.\n",
        "# Do not edit this file directly.\n",
    ]
    lines += [f"Config.{key} = {value};\n" for key, value in values.items()]
    GENERATED.write_text("".join(lines), encoding="utf-8")

    modules = sorted(MODULES.glob("*.script"))
    chunks = [
        "# Curruption Plymouth theme.\n",
        "# Generated by scripts/build.py from theme/modules/ and config/theme.conf.\n",
        "# Do not edit this file directly; edit the modules and rebuild.\n",
    ]
    for path in modules:
        chunks += [f"\n# ==== {path.name} ====\n", path.read_text(encoding="utf-8")]
    OUTPUT.write_text("".join(chunks), encoding="utf-8")

    print(f"Built {OUTPUT.relative_to(ROOT)} from {len(modules)} modules:")
    for path in modules:
        print(f"  {path.name}")


if __name__ == "__main__":
    main()
